apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: prometheustest
spec:
  strategy:
    canary:
      analysis:
        templates:
        # name of AnalysisTemplate
        - templateName: success-rate
        # When it begins (after the 1-minute pause)
      canaryService: prometheustestcanary 
      stableService: prometheustest
      trafficRouting:
        nginx:
          stableIngress: prometheustest
      steps:
      - setWeight: 10
      - pause: {duration: 10}
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 50
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  replicas: 1
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: prometheustest
  template:
    metadata:
      labels:
        app: prometheustest
    spec:
      containers:
      - name: prometheustest
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080