apiVersion: v1
kind: Service
metadata:
  name: nginx-helm-canary
spec:
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app: nginx-helm-canary
