apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-helm
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: nginx-helm.34.93.190.171.nip.io 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-helm
                port:
                  number: 3000